name: Deploy NextCV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Do the build
      run: |
        npm install
        npm run build
        node_modules/.bin/lessc --clean-css="--s1 --advanced --compatibility=ie8" src/less/main.less public/css/main.css

    - name: Run cache busters
      run: |
        mkdir -p cvb/{css,js}
        cp -vr public/img cvb
        cp -v public/js/manifest.edn cvb
        cp -v public/js/main.js "cvb/js/${GITHUB_SHA}.js"
        cp -v public/css/main.css "cvb/css/${GITHUB_SHA}.css"
        cat public/index.html | sed -e "s#/js/main.js#/js/${GITHUB_SHA}.js#" -e "s#/css/main.css#/css/${GITHUB_SHA}.css#" > "cvb/index.html"

    - name: Deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
